#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------


matrix:
    include:
        - os: linux
          compiler: clang
          dist: bionic
          language: cpp
        - os: linux
          compiler: gcc
          python: 3.4
          dist: xenial
          language: python
        - os: linux
          compiler: gcc
          python: 3.5
          dist: bionic
          language: python
        - os: linux
          compiler: gcc
          python: 3.6
          dist: bionic
          language: python
        - os: linux
          compiler: gcc
          python: 3.7
          dist: bionic
          language: python
        - os: linux
          compiler: gcc
          python: 3.8
          dist: bionic
          language: python
        - os: osx
          osx_image: xcode7
          compiler: clang
          language: cpp
        - os: osx
          osx_image: xcode10.1
          compiler: clang
          language: cpp

# http://docs.travis-ci.com/user/apt/
addons:
    apt:
        sources:
            - boost-latest
        packages:
            - libboost-dev
            - python3
            - python3-dev
            - python3-pip

install:
    - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git contrib/libosmium
    - git clone --quiet --depth 1 https://github.com/mapbox/protozero.git contrib/protozero
    - git clone --quiet --depth 1 https://github.com/pybind/pybind11.git contrib/pybind11
    - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
        pip3 install --user -q nose mock shapely setuptools;
      else
        pip3 install -q nose mock shapely setuptools;
      fi

script:
    - python3 --version
    - python3 setup.py build
    - cd test
    - python3 run_tests.py

