#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

dist: bionic

matrix:
    include:
        - os: linux
          compiler: clang
          python: 3.7
        - os: linux
          compiler: gcc
          python: 3.4
        - os: linux
          compiler: gcc
          python: 3.5
        - os: linux
          compiler: gcc
          python: 3.6
        - os: linux
          compiler: gcc
          python: 3.7
        - os: linux
          compiler: gcc
          python: 3.8
        - os: osx
          osx_image: xcode7
          compiler: clang
        - os: osx
          osx_image: xcode10.1
          compiler: clang

# http://docs.travis-ci.com/user/apt/
addons:
    apt:
        sources:
            - boost-latest
        packages:
            - libboost-dev
            - python3-dev

install:
    - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git contrib/libosmium
    - git clone --quiet --depth 1 https://github.com/mapbox/protozero.git contrib/protozero
    - git clone --quiet --depth 1 https://github.com/pybind/pybind11.git contrib/pybind11
    - pip3 install -q nose mock shapely setuptools

script:
    - python3 --version
    - python3 setup.py build
    - cd test
    - python3 run_tests.py

